### ISSUE TITLE
Tratamento de data nula, 0 ou 1899/12/30

### ISSUE THREAD

**Issue by almp1** [silvioprog/rutils#2]
Olá Silvio, tudo bem ?
Fiz uma alteração na RUtils para tratar datas na serialização do Json.
Fiz da seguinte forma

Adicionei a var abaixo antes da declaração do type
var
  bCheckData: Boolean;

type
  TArrayOfString = array of string;

Declarei 3 novas funções abaixo do JsonToPath
function JSONToPath(AJSON: TJSONArray): string;
function GetTDate(F: Double): String;
function GetTTime(F: Double): String;
function GetTDateTime(F: Double): String;

Implementei as funções conforme abaixo
function GetTDate(F: Double): String;
begin
  if (F = 0) and (bCheckData) then
    Result := ''
  else
    Result := DateToStr(F);
end;

function GetTTime(F: Double): String;
begin
  if (F = 0) and (bCheckData) then
    Result := ''
  else
    Result := TimeToStr(F);
end;

function GetTDateTime(F: Double): String;
begin
  if (F = 0) and (bCheckData) then
    Result := ''
  else
    Result := DateTimeToStr(F);
end;

Em todas as procedures de serialização que tratam datas fiz a seguinte alteração
          case PI^.PropType^.Name of
            'TDate': AJson.Add(PI^.Name, GetTDate(F));
            'TTime': AJson.Add(PI^.Name, GetTTime(F));
            'TDateTime': AJson.Add(PI^.Name, GetTDateTime(F));
          else

Para que a data retorne uma string vazia quado executamos o método
ObjectToJSON

É só setar a variável
  bCheckData := True;

Em uso conjunto com o brook, se preferir na unit, brokers, declare a RUtils e na inicialização passe tru para o bCheckData.

uses
   RUtils

initialization
  bCheckData := True;

Espero ter ajudado, fiz isso pois não encontrei outra forma de trazer a data em branco para minha pagina web serializando um objeto tiopf

Se você julgar que a alteração pode ser proveitosa para outros usuários, disponibilize em um próximo release.

Abraços,

**Comment by silvioprog** [comment]
Olá @almp1 , tudo bem? Estou refatorando a RUtils para unificá-la a outro projeto (também open source), então suas alterações poderão ser aplicadas diretamente lá. Estou fazendo isto para unificar os projetos que mantenho, facilitando uma possível documentação e testes. Abração!
