### ISSUE TITLE
Correction in the function Extract()

### ISSUE THREAD

**Issue by rchastain** [silvioprog/rutils#3]
Hello!

I have just downloaded rutils. It looks interesting. But the following code needs to be corrected, isn't it?

    VRegEx.ModifierI := rmModifierI in AModifiers;
    VRegEx.ModifierR := rmModifierI in AModifiers;
    VRegEx.ModifierS := rmModifierI in AModifiers;
    VRegEx.ModifierG := rmModifierI in AModifiers;
    VRegEx.ModifierM := rmModifierI in AModifiers;
    VRegEx.ModifierX := rmModifierI in AModifiers;

Best regards.

Roland

**Comment by rchastain** [comment]
And the same correction has to be done in the three functions.

**Comment by silvioprog** [comment]
Patch please! :-)

**Comment by rchastain** [comment]
Sorry but I don't see what you mean. The correction to be done is obvious, isn't it?

**Comment by silvioprog** [comment]
Indeed. I really need to change my glasses. :-) Fixed in https://github.com/silvioprog/rutils/commit/a924a007307e2641225140c2653f0f466a1e5c06. Thank you for reporting!

**Comment by rchastain** [comment]
You are welcome. ;)
